#!/bin/bash

dir=`dirname $0`

version=9.12.0.0
polopolyversion=9.12.0
luceneversion=2.3.1

# if the JAR doesn't exist in the current directory, this is probably
# a symlink to the script
if [ ! -f $dir/pcmd-$version.jar ] 
then
    realscript=`readlink $0`
    if [ "" != "$realscript" ]
    then
	dir=`dirname $realscript`
    fi
fi

# try to find a running jboss and use it's jbossall-client
# External JBoss:
jbossmain=`ps aux | grep org.jboss.Main | grep -o "[^ ]*/bin/run.jar" | grep -v ]`

if [ "" != "$jbossmain" ]
then
    jbossdir=`dirname $jbossmain`
    jbossjar=$jbossdir/../client/jbossall-client.jar
fi

if [ ! -f "$jbossjar" ] 
then
    jbossjar=$dir/jbossall-client.jar
fi

if [ ! -f "$jbossjar" ] 
then
    jbossjar=~/.m2/repository/jboss/jbossall-client/4.0.5.GA/jbossall-client-4.0.5.GA.jar
fi

if [ ! -f "$jbossjar" ] 
then 
    cd $dir
    mvn dependency:resolve
fi

if [ -f "$jbossjar" ] 
then
    classpath=$jbossjar
else 
    echo "Could not find jbossall-client.jar, neither in $dir, nor in $jbossjar and JBoss doesn't seem to be running locally."
    exit;
fi

peardir=`ps aux | grep -v grep | grep -m 1 -o '[^: =]*polopoly/pear/' | head -n 1`

if [ "" != "$peardir" ]
then
    polopolyjar=$peardir../install/lib/polopoly.jar
    lucenejar=$peardir../install/lib/lucene-core-2.3.1.jar
    
    if [ ! -f "$lucenejar" ]
    then
        lucenejar=$peardir../install/lib/lucene-core-1.9.1.jar
    fi
fi

if [ ! -f "$polopolyjar" ] 
then
    polopolyjar=$dir/polopoly-$polopolyversion.jar
fi

if [ ! -f "$polopolyjar" ] 
then
    polopolyjar=~/.m2/repository/com/polopoly/polopoly/$polopolyversion/polopoly-$polopolyversion.jar 
fi

if [ ! -f "$polopolyjar" ] 
then 
    cd $dir
    mvn dependency:resolve
fi

if [ -f "$polopolyjar" ]
then
    classpath=$classpath:$polopolyjar
else
    echo "Could not find Polopoly JAR, neither in $peardir../install, nor in $dir nor in $polopolyjar.";
    exit;
fi

if [ ! -f "$lucenejar" ]
then
    lucenejar=$dir/lucene-core-$luceneversion.jar
fi

if [ ! -f "$lucenejar" ]
then
    lucenejar=$dir/lucene-core-1.9.1.jar
fi

if [ ! -f "$lucenejar" ]
then
    lucenejar=$dir/lucene-core-2.3.1.jar
fi

if [ ! -f "$lucenejar" ]
then
    lucenejar=~/.m2/repository/org/apache/lucene/lucene-core/$luceneversion/lucene-core-$luceneversion.jar
fi

if [ ! -f "$lucenejar" ] 
then 
    cd $dir
    mvn dependency:resolve
fi

if [ -f "$lucenejar" ]
then
    classpath=$classpath:$lucenejar
else
    echo "Could not find Lucene JAR, neither in $peardir../install, nor in $bin nor in $lucenejar.";
    exit;
fi

jar=$dir/pcmd-$version.jar

if [ ! -f "$jar" ]
then
    # check if we can use JAR from MVN repository rather than current dir
    jar=~/.m2/repository/com/polopoly/pcmd/$version/pcmd-$version.jar

    if [ ! -f $jar ]
    then
        cd $dir
        mvn dependency:resolve
    fi
    
    if [ ! -f $jar ]
    then
	echo "The JAR for PCMD did not exist either in $dir, nor in Maven repository $jar.";
	exit;
    fi
fi

if [ "" != "$POLOPOLY_SERVER" ]
then
        options="$options --server=$POLOPOLY_SERVER"
fi

if [ "" != "$POLOPOLY_USER" ]
then
        options="$options --user=$POLOPOLY_USER"
fi

if [ "" != "$POLOPOLY_PASSWORD" ]
then
        options="$options --password=$POLOPOLY_USER"
fi

if [ "$1" == "--verbose" ]
then
        echo "Using $jbossjar, $polopolyjar, $lucenejar and $jar."
fi

java -cp $classpath:$jar com.polopoly.pcmd.Main$options "$@"
