#!/bin/bash

dir=`dirname $0`

version=9.12.0.0
polopolyversion=9.12.0
luceneversion=2.3.1

# if the JAR doesn't exist in the current directory, this is probably
# a symlink to the script
if [ ! -f $dir/pcmd-$version.jar ] 
then
    realscript=`readlink $0`
    if [ "" != "$realscript" ]
    then
	dir=`dirname $realscript`
    fi
fi

# if jbossall-client exists in the current directory, use it
if [ -f $dir/jbossall-client.jar ] 
then
        classpath=$dir/jbossall-client.jar
else
        # otherwise, try to find a running jboss and use it's jbossall-client
        # External JBoss:
        jbossmain=`ps -ef | grep org.jboss.Main | grep -o "[^ ]*/run.sh" | grep -v ]`

        if [ "" = "$jbossmain" ]
        then
	    # Internal JBoss
	    jbossmain=`ps -ef | grep -o "[^ ]*/bin/run.jar" | grep -v ]`

            if [ "" = "$jbossmain" ]
            then
                echo "JBoss must either be running on the machine you are running pcmd from or the jbossall-client.jar must be placed in the same directory as the pcmd script.";
                exit;
	    fi
        fi

        jbossdir=`dirname $jbossmain`
        classpath=$jbossdir/../client/jbossall-client.jar
fi

peardir=`ps -ef | grep -v grep | grep -m 1 -o '[^: =]*polopoly/pear/' | head -n 1`

if [ "" != "$peardir" ]
then
    polopolyjar=$peardir../install/lib/polopoly.jar
    lucenejar=$peardir../install/lib/lucene-core-2.3.1.jar
    
    if [ ! -f "$lucenejar" ]
    then
        lucenejar=$peardir../install/lib/lucene-core-1.9.1.jar
    fi
fi
 
if [ ! -f "$polopolyjar" ] 
then
    polopolyjar=$dir/polopoly-$polopolyversion.jar
fi

if [ ! -f "$polopolyjar" ] 
then
    polopolyjar=~/.m2/repository/com/polopoly/polopoly/$polopolyversion/polopoly-$polopolyversion.jar 
fi

if [ -f "$polopolyjar" ]
then
    classpath=$classpath:$polopolyjar
else
    echo "Could not find Polopoly JAR, neither in $peardir../install, nor in $dir nor in $polopolyjar.";
    exit;
fi

if [ ! -f "$lucenejar" ]
then
    lucenejar=$dir/lucene-core-$luceneversion.jar
fi

if [ ! -f "$lucenejar" ]
then
    lucenejar=~/.m2/repository/org/apache/lucene/lucene-core/$luceneversion/lucene-core-$luceneversion.jar
fi

if [ -f "$lucenejar" ]
then
    classpath=$classpath:$lucenejar
else
    echo "Could not find Lucene JAR, neither in $peardir../install, nor in $bin nor in $lucenejar.";
    exit;
fi

jar=$dir/pcmd-$version.jar

if [ ! -f "$jar" ]
then
    # check if we can use JAR from MVN repository rather than current dir
    jar=~/.m2/repository/com/polopoly/pcmd/$version/pcmd-$version.jar

    if [ ! -f $jar ]
    then
	echo "The JAR for PCMD did not exist either in $dir, nor in Maven repository $jar.";
	exit;
    fi
fi

if [ "" != "$POLOPOLY_SERVER" ]
then
        options="$options --server=$POLOPOLY_SERVER"
fi

if [ "" != "$POLOPOLY_USER" ]
then
        options="$options --user=$POLOPOLY_USER"
fi

if [ "" != "$POLOPOLY_PASSWORD" ]
then
        options="$options --password=$POLOPOLY_USER"
fi

java -cp $classpath:$jar com.polopoly.pcmd.Main$options "$@"
